---
# file: practice/2.application-abstractions/2.replicaset/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
  - image: nginx:stable-alpine-perl
    name: nginx
    ports:
    - containerPort: 80
...
