---
# file: practice/2.application-abstractions/4.resources/deployment-with-resources.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:stable-alpine-perl
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10
            memory: 100Mi
          limits:
            cpu: 10
            memory: 100Mi
...
